config/routes.rb
Blog::Application.routes.draw do
  
  root :to => "articles#index"
  
  devise_for :users
  
  resources :articles do
    resources :comments
  end
  
  resources :tags
  
  match "/sitemap" => "sitemap#index", via: [:get], :as => :sitemap, :defaults => {:format => :xml}

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
 
    if user.role? :Admin
      can :manage, :all
      can :create, Article
    elsif user.role? :Moderator
      can :read, [Article, Comment]
      can [:edit, :update], Comment
    elsif user.role? :Member
       can :read, :all
       can :create, [Article, Comment]
       can [:edit, :update], Comment
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  
  validates_presence_of :title, :body
  validates_uniqueness_of :title

  validates_presence_of :user_id
  validates_numericality_of :user_id
  belongs_to :user
  
  attr_writer :tag_names
  after_save :assign_tags
  
  scope :published, lambda { where('published = ?', true)}
  scope :ordered, order('created_at DESC')

  def tag_names
    @tag_names || tags.map(&:name).join(' ')
  end
  
  
  private
  
    def assign_tags
      if @tag_names
        self.tags = @tag_names.split(/\,/).map do |name|
          name.rstrip! # delete all spaces to the right from tag
          name.lstrip! # delete all spaces to the left from tag
          Tag.find_or_create_by_name(name)
        end
      end
    end  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  
  validates_presence_of :name, :email, :body
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :articles, :through => :taggings
  
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  
  belongs_to :article
  belongs_to :tag
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :roles
  has_many :articles

  before_create :setup_role
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
         
  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end
  
  private
  def setup_role
    if self.role_ids.empty?
      self.role_ids = [3]
    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource  
  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.ordered.published.page(params[:page]).per(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new(:article => @article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :tag_names, :published)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @article = @comment.article
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@article, :notice => 'Comment was successfully created.') }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { redirect_to(@article, :notice => 'Comment could not be saved. Please fill in all fields.') }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:article_id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to(@article, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:article_id])
    @comment.destroy
    
    respond_to do |format|
      format.html { redirect_to(@article, :notice => 'Comment was successfully deleted.') }
      format.json  { head :ok }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :name, :email, :body)
    end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  layout nil

  def index
    @articles = Article.all
    headers["Content-Type"] = "text/xml"
    respond_to do |format|
      format.xml { render :layout => false }
    end
  end

  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @articles = @tag.articles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/views/articles/_article.html.erb
<div class="article_header">
	<h2><%= article.title %></h2>
	By <%= article.user.email %> on <%= article.created_at.strftime("%B %d %Y") %><br />
</div>

<%= truncate(article.body, :length => 500) %><br />
<%= link_to 'Show', article %>

<% if can? :update, article %>
	| <%= link_to 'Edit', edit_article_path(article) %> |
<% end %>

<% if can? :destroy, article %>
	<%= link_to 'Destroy', article, data: {:confirm => 'Are you sure?'}, :method => :delete %>
<% end %>

<br /><br />

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tag_names, "Tags" %><br>
    <%= f.text_field :tag_names %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= check_box("article", "published" ) %>
    <%= "Publish article" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= paginate @articles %>
<div class="article_index">
	<%= render @articles %>
</div>

<br />
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div id="article-content" class="span-17">
	<div class="article_title">
		<h1><%= @article.title %></h1>
	</div>
	<div class="article_body">
    	<p>By <%= @article.user.email %>
    	    on <%= @article.created_at.strftime("%B %d, %Y") %>
    	</p>

		<p>
			<%= @article.body %>
		</p>
        
		<p>Tags:
			<% @article.tags.each do |tag|%>
			<%= tag.name %>
			<% end %>
		</p>
	</div>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>


<h2>Comments</h2>

<div id ="comments">
	<%= render @article.comments %>
</div>

<%= form_for([@article, @comment]) do |f| %>
	<div class="field">
		<%= f.label :name %><br />
	    <%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</div>
	<p><%= f.submit %></p>
<% end %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>

	<% unless comment.id.nil? %>
		<div id = "comment_author">
			<%= comment.name %>
			<%= link_to 'Edit', edit_article_comment_path(@article, comment) %>
			<%= link_to 'Delete', article_comment_path(@article, comment), data: {:confirm => 'Are you sure?'}, :method => :delete %>
		</div>
		<div id = "comment_created_at">
			<%= comment.created_at %>
		</div>
		<div id = "comment_text">
			<p><%= comment.body %></p>
		</div>
	<% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for([@article, @comment]) do |f| %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</div>
	<p><%= f.submit %></p>
<% end %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article_id %></td>
        <td><%= comment.name %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blog Tutorial for Rails 4</title>
	<%= stylesheet_link_tag 'scaffold' %>
	<%= stylesheet_link_tag 'screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'print', :media => 'print' %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class= "container">
		<div class="span-17 colborder" id="content">
			<%= yield %>
		</div>
		
		<div class="span-4 last" id="sidebar">
			<%= render(:partial => 'shared/side') %>
		</div>
		
	</div>
</body>
</html>

app/views/shared/_side.html.erb
<div id="tag_title">  
	<h3>Tags</h3>
</div>

<div id= "tags" class = "span-4 last">
	<% cache('all_tags') do %> 
	<% for tag in Tag.all.order('name ASC') %>
	<li><%= link_to "#{tag.name}", tag_path(tag) %></li>
	<% end %>
</div>

<% end %>

app/views/tags/show.html.erb
<%= link_to 'Back to all articles', articles_path %>

<h2>Articles with tag <%= @tag.name %></h2>

<%= render @articles %>